- name: Docker install
  hosts: localhost
  become: true

  tasks:
    - name: Step 1
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        update_cache: true

    - name: Step 2
      ansible.builtin.command: sh docker_pre_install.sh
      register: output
      changed_when: output.rc != 0

    - name: Step 3
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: true

    # To apply the new group membership, log out of the server and back in,
    # or type the following: su - ${USER}
    - name: Step 4
      ansible.builtin.user:
        name: "{{ ansible_facts.env['SUDO_USER'] }}"
        groups: docker
        append: true
