- name: Git install
  hosts: localhost
  gather_facts: false
  become: true

  vars:
    git_name: "Vyacheslav Ratushnyi"
    git_email: "ratushnyyvm@gmail.com"

  tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        update_cache: true

    - name: Set name
      community.general.git_config:
        name: user.name
        value: "{{ git_name }}"

    - name: Set email
      community.general.git_config:
        name: user.email
        value: "{{ git_email }}"
